package Package;

interface TokenList {
    final byte
            NO_TYPE=0,
            NUM=1,
            DIGIT=2,
            INPUT_SIGN=3,
            EPSILON=4,
            START=5,
            NOT_FINAL=6,
            KOMMA=7,
            IDENT=8,
            OPEN_PAR=9,
            CLOSE_PAR=10,
            PLUS=11,
            MINUS=12,
            MULT=13,
            DIV=14,
            EXPRESSION=15,
            RIGHT_EXPRESSION=16,
            TERM=17,
            RIGHT_TERM=18,
            OPERATOR=20,
            PROGRAM=21,
            ID=23,
            ERROR=24,
            FLOAT=25,
            SEMICOLON=26,
            OPEN_ACC=27,
            CLOSE_ACC=28,
            LINECOMMEN=29,
            MULTILINECOMMEN=30,
            STRING=31,
            EQUAL=32,
            ZWEIEQUAL=33,
            LESS=34,
            LESSEQUAL=35,
            MORE=36,
            MOREEQUAL=37,
            NOTEQUAL=38,
            Keyword=22;
}
